### ISSUE TITLE
Getting object list for a claim

### ISSUE THREAD

**Issue by loboneto** [auth0/JWTDecode.Android#38] opened 2019-05-03 14:20 UTC
I'm currently using the library in my android app for receiving a token with a claim called "realm_access", but i can't get the list of strings inside him.

"realm_access": {
   "roles": [
     "role-one",
     "role-two"
   ]
 },

**Comment by lbalmaceda** [comment] 2019-05-03 16:40
@loboneto this library doesn't support that for now. We have a task in our backlog to review adding this feature to our jwt libraries, but is not a priority for now. I'll close this issue as it's a dupe of https://github.com/auth0/JWTDecode.Android/issues/21. Let's keep the conversation there. Thanks

**Closed by lbalmaceda** 2019-05-03 16:40 UTC
